### ISSUE TITLE
Phys 401: lambda should be lowercase

### ISSUE THREAD

**Issue by kevinlinxc** [DonneyF/formula-sheets#12]
![image](https://user-images.githubusercontent.com/44324811/160048071-2832aa9c-17e9-4f97-b3f6-b1e752f495c6.png)
![image](https://user-images.githubusercontent.com/44324811/160048080-dbae0fc0-165c-4a1b-8924-906cb8067625.png)

**Comment by DonneyF** [comment]
Hi, in this case <img src="https://render.githubusercontent.com/render/math?math=\Lambda"> (capitalized) is our scalar function. I think I followed my prof's notes for this and not Griffiths.
